### PR TITLE
Fancier row removal

### LINKED ISSUE #55: Animate row removal

### PR DESCRIPTION
**Pull request by dealingwith**
closes #55

### CODE REVIEW

**Comment by dealingwith** [comment]
@jamespeilunli why isn't this working?

**Comment by dealingwith** [comment]
Oh, hang on, I might be getting there.

**Comment by dealingwith** [comment]
Ok, now it works...sometimes... 😛

**Comment by jamespeilunli** [comment]
You were just missing the `draw` method. Changing the `gameboard` matrix doesn't do anything on the actual screen until `draw` is called. (all methods and vars mentioned are in `game.rb`)

**Comment by jamespeilunli** [comment]
It was probably working sometimes because you pressed a key, which makes `draw` called.

**Comment by jamespeilunli** [comment]
I don't think we should make the pause get progressively longer when more rows are cleared. I just think its kinda weird.

**Comment by dealingwith** [comment]
> I don't think we should make the pause get progressively longer when more
rows are cleared. I just think its kinda weird

Agree.

**Comment by dealingwith** [comment]
@jamespeilunli ok I think this is ready!

**Review by jamespeilunli — APPROVED** [review]
Looks good! I really like the pausing feature so I can rest my eyes while playing.

**Pull request merged**
