### PR TITLE
Allow tetromino to fall after collision save

### LINKED ISSUE #46: Allow tetrominos to fall after they've been "saved" by the last chance move before collision detect
Screenshot from 2021-08-16 11-59-29
See the orange tetromino; it's floating. This is because right when the orange tetromino fell on the purple tetromino, the collision detect gave the orange tetromino a last chance to move out of the way, which it did. But, the collision detect set the orange tetromino to "dead" anyways.

### PR DESCRIPTION
**Pull request by jamespeilunli**
closes #46 
Read #46 to see details.

Currently it works-ish, but you can run into a square with no consequence until `hard_dead` is set to true.

### CODE REVIEW

**Comment by jamespeilunli** [comment]
I think I fixed it.

**Comment by dealingwith** [comment]
You ended up reverting some of the updates from #38 was that on purpose?

**Comment by jamespeilunli** [comment]
No, I think I started working on this before you pushed the changes for #38. Lets try to incorporate it back.

**Comment by dealingwith** [comment]
Did you merge main into this branch? I looks like it but I don't see the merge commit. 🤔

**Comment by jamespeilunli** [comment]
I don't think so..

**Comment by jamespeilunli** [comment]
I just made a very minor change, when acellerating `fall_rate` was being multiplied by 4, while when unacellerating it was being divided by 3. I've changed both to 5.

**Comment by jamespeilunli** [comment]
ok, I resolved the conflicts. @dealingwith, on our next Sunday session, can you help me with the "correct" way to resolve conflicts and merge?

Everything is ready for review.

**Review by dealingwith — APPROVED** [review]
not bad

**Pull request merged**
