### PR TITLE
Add tetromino rotate mechanics

### LINKED ISSUE #20: Add rotate mechanics for tetrominos

### PR DESCRIPTION
**Pull request by jamespeilunli**
Tetromino can now rotate, using the Matrix.transpose method and some mapping to reverse each row (transposing doesn't actually rotate).

If you spam up arrow (the rotate button), you won't actually fall, but this can be changed because eventually we will be implementing accelerated falling.

I'm making this a draft because my previous pull request hasn't been approved, and I don't want this one approved before that one.

### CODE REVIEW

**Comment by dealingwith** [comment]
Make sure to un-mark as "Draft" if it's ready for review

**Comment by dealingwith** [comment]
Also fix indentation

**Comment by jamespeilunli** [comment]
oops

**Review by dealingwith — APPROVED** [review]
Looking good!

**Pull request merged**
