### PR TITLE
Collision detection

### LINKED ISSUE #26: Implement better tetromino collision detection

### PR DESCRIPTION
**Pull request by jamespeilunli**
This has a bug where in `tetris.rb` the gameboard matrix is blank.

### CODE REVIEW

**Comment by jamespeilunli** [comment]
still messy

**Comment by dealingwith** [comment]
Looking better, though. My only feedback so far would be that you're keeping `gameboard_width` and height in two places...

**Comment by dealingwith** [comment]
Also you've implemented some of the refactorings I worked on yesterday, which is great. I think we should get this into a mergable state and then work on any refactoring/improvements in a separate PR.

**Comment by dealingwith** [comment]
> you're keeping gameboard_width and height in two places

and `size`

I'm going to resolve the conflicts in this branch and then work on that minor bit of refactoring...

**Review by dealingwith — APPROVED** [review]

**Pull request merged**
