### PR TITLE
Convert to Ruby2D

### LINKED ISSUE #7: Document dependency managment

### PR DESCRIPTION
**Pull request by dealingwith**
closes #7 

Originally I was just trying to manage the project's dependencies by putting the previous library, `rubygame` in a Gemfile so we can use bundler to manage dependencies. Then I discovered `rubygame` is ~10 years old and unmaintained. This caused 🚨 so I went back to `Ruby2D` to see if we could use it instead.

It installed easily and ran the first time. ✨ 
I was able to quickly port @jamespeilunli's code from #11 to Ruby2d 🎉 

So this PR:

* adds Gemfile
* refactors `tetris.rb` and `tetrominos.rb` to ruby2d

TODO: 

- [x] Figure out why two tetrominoes are being drawn in yellow (I think the orange one is yellow).
- [x] Write instructions in README.md

### CODE REVIEW

**Comment by dealingwith** [comment]
@jamespeilunli note I've converted indentation to 2 space

**Comment by jamespeilunli** [comment]
Looks like that reinstall of Ubuntu helped something; Ruby2D works for me now.
Ruby2D works for me now??

**Comment by dealingwith** [comment]
Did you follow the instructions in the README and use Bundler?

>

**Comment by jamespeilunli** [comment]
Sorry, I didn't see the README.

I saw that Ruby2d used SDL (in Linux), and I thought I had all the dependencies I needed since Rubygame also used SDL. But, when I ran `sudo gem install ruby2d`, it alerted me that I needed to install these packages: `libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev`, so I ran `sudo apt-get install *those packages*`. Running `sudo gem install ruby2d` after that threw no errors, and I tested it out on a test file with the example program on the [Ruby2d homepage](http://www.ruby2d.com/)  and it worked.

**Pull request merged**
