### PR TITLE
Add downwards drop and acceleration

### LINKED ISSUE #25: Allow different key presses to be evaluated at the same time
Right now, if I press 2 different keys (like up and right), only one of them will be evaluated (if right was evaluated, that means that the tetromino moved right but the tetromino didn't rotate).

### LINKED ISSUE #43: Allow down keypress to move tetromino all the way to the bottom

### PR DESCRIPTION
**Pull request by jamespeilunli**
closes #43 

You can now press the down arrow to accelerate the tetromino downwards. You can also press the space bar to instantly drop the tetromino to the lowest available space in the current x position.

I now realize I accidentally closed #25 in this PR too. Yay!

### CODE REVIEW

**Comment by dealingwith** [comment]
You're on fire! 🔥

**Comment by jamespeilunli** [comment]
Thank you!

**Comment by jamespeilunli** [comment]
It also looks like `moved` is partially no longer needed. Uhhhhhh

This:
```
on :key_held do |event|
  if event.key == "down"
    if !moved
      game.tetromino.moved = game.tetromino.move(event.key)
      game.update_gameboard
      game.draw([0, 0], size)
    end
  end
end
```
does the same thing as this:
```
on :key_held do |event|
  if event.key == "down"
    game.tetromino.moved = game.tetromino.move(event.key)
    game.update_gameboard
    game.draw([0, 0], size)
  end
end
```
But when I comment out `game.tetromino.moved = game.tetromino.move(event.key)`, I can no longer move the tetromino.

**Review by dealingwith — APPROVED** [review]
Looks great!

**Pull request merged**
