### PR TITLE
Adds scoreboard

### LINKED ISSUE #44: Detect Tetris (4 rows at once)

### LINKED ISSUE #47: Add score component

### PR DESCRIPTION
**Pull request by dealingwith**
score

### CODE REVIEW

**Comment by jamespeilunli** [comment]
closes #47 
closes #44 

EDIT: Oh wait only the first comment can do that

**Comment by dealingwith** [comment]
@jamespeilunli no it looks like the issue linking worked

is this good to go?

**Comment by jamespeilunli** [comment]
Good to go!

I think I added the issue linking after I saw it not work though.

**Review by jamespeilunli — APPROVED** [review]
Great!

**Comment by jamespeilunli** [comment]
So #48 should have conflicts now.

**Pull request merged**
